# Build stage
FROM maven:3.8.1-openjdk-21 as builder

WORKDIR /app

COPY backend/SMA .

RUN mvn clean package -DskipTests

# Runtime stage
FROM openjdk:21-slim

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
